# Generated by Django 4.0.4 on 2022-09-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_outpass_api', '0002_alter_outpassform_proofletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpassform',
            name='proofletter',
            field=models.FileField(upload_to='proofphotos/%Y/%m/%d'),
        ),
    ]
