# Generated by Django 4.0.4 on 2022-09-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_outpass_api', '0003_alter_outpassform_proofletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
