# Generated by Django 4.0.4 on 2022-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_outpass_api', '0004_delete_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassform',
            name='appliedtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outpassformaccepted',
            name='appliedtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpassformaccepted',
            name='proofletter',
            field=models.FileField(upload_to='acceptproofphotos/%Y/%m/%d'),
        ),
    ]
