# Generated by Django 4.0.4 on 2022-09-25 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_outpass_api', '0005_outpassform_appliedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpassform',
            name='appliedtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 19, 39, 43, 858095)),
        ),
        migrations.AlterField(
            model_name='outpassformaccepted',
            name='appliedtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 19, 39, 43, 859095)),
        ),
    ]
