# Generated by Django 4.0.4 on 2022-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_outpass_api', '0006_alter_outpassform_appliedtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpassform',
            name='appliedtime',
        ),
        migrations.RemoveField(
            model_name='outpassformaccepted',
            name='appliedtime',
        ),
    ]
